name: Deploy DataLake Builder

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key'
        required: true
      aws_session_token:
        description: 'AWS Session Token'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}
          aws-session-token: ${{ github.event.inputs.aws_session_token }}
          aws-region: us-east-1

      - name: Get SQS Queue URL from Parameter Store
        id: get_sqs_url
        run: |
          export SQS_QUEUE_URL=$(aws ssm get-parameter --name "sqs_queue_url" --query "Parameter.Value" --output text --region us-east-1)
          echo "SQS_QUEUE_URL=$SQS_QUEUE_URL"
          echo "::set-output name=sqs_queue_url::$SQS_QUEUE_URL"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init

      - name: Deploy DataLake with Terraform
        run: terraform apply -auto-approve \
          -var "sqs_queue_url=${{ steps.get_sqs_url.outputs.sqs_queue_url }}"

      - name: Debug Terraform Outputs
        run: terraform output
