name: Deploy MongoDB Cluster on AWS

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  validate-aws-credentials:
    name: Validate AWS Credentials
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    needs: validate-aws-credentials
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
  
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false
  
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Debug Terraform Output
        run: terraform output

      - name: Capture Terraform Outputs
        id: capture-outputs
        run: |
          echo "::set-output name=config_server_ip::$(terraform output -raw config_server_ip)"
          echo "::set-output name=mongos_ip::$(terraform output -raw mongos_ip)"
          echo "::set-output name=shard_ips::$(terraform output -json shard_ips)"

  
      - name: Upload Terraform Files
        uses: actions/upload-artifact@v3
        with:
          name: terraform-files
          path: |
            .terraform/
            terraform.tfstate

  test-mongodb-cluster:
    name: Test MongoDB Cluster
    runs-on: ubuntu-latest
    needs: deploy-infrastructure

    steps:
      - name: Get Cluster IPs
        run: echo "Using CONFIG_SERVER_IP=${{ needs.deploy-infrastructure.outputs.config_server_ip }}, MONGOS_IP=${{ needs.deploy-infrastructure.outputs.mongos_ip }}, SHARD_IPS=${{ needs.deploy-infrastructure.outputs.shard_ips }}"


      - name: Install MongoDB Client
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-8.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu $(lsb_release -cs)/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org jq
          sudo systemctl enable mongod
          sudo systemctl start mongod
          
      - name: Initialize Replica Sets on Shards
        run: |
          for ip in $(echo $SHARD_IPS | jq -r '.[]'); do
            mongo --host $ip:27017 --eval "rs.initiate()"
          done

      - name: Configure Shards on Mongos
        run: |
          for ip in $(echo $SHARD_IPS | jq -r '.[]'); do
            mongo --host $MONGOS_IP:27017 --eval "sh.addShard('$ip:27017')"
          done

      - name: Enable Sharding for Database
        run: mongo --host $MONGOS_IP:27017 --eval "sh.enableSharding('my_database')"

  cleanup:
    name: Cleanup Resources
    runs-on: ubuntu-latest
    needs: [deploy-infrastructure, test-mongodb-cluster]
    if: always()

    steps:
      - name: Download Terraform Files
        uses: actions/download-artifact@v3
        with:
          name: terraform-files


      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init


      - name: Destroy Terraform Resources
        run: terraform destroy -auto-approve

